### ISSUE TITLE
Do we really need setup.py.bak？

### ISSUE THREAD

**Issue by woodpenker** [dongrixinyu/ffio#2]
BTW:
It seems that some codes of `pyFFmpeg/main.c` are the same with `pyFFmpeg/extractFrame.c`, so I am curious about what is the usage of `main.c`?

**Comment by koisi-io** [comment]
The project is currently in a 'quick-start' phase, so there may be some parts included for testing convenience. For now, I would recommend focusing on input_stream_parser.py or the sections used in the Examples.
